-- Этот файл был сгенерирован тНавигатор v23.1-3979-g6d70bbb6d3f7.
-- Copyright (C) Рок Флоу Динамикс 2005-2023.
-- Все права защищены.

INCLUDE
'INCLUDE/BOSTemplate_PVT.inc' /


DENSITY
-- oil water gas  (sc)
   900 1030  1.22 /


ROCK
-- pressure rock-compres (rock-matrix-compres block-compres porosity Poisson-coef)
   200      0.00005      /


STCOND
 15.56 1.01325 /
INCLUDE
'INCLUDE/BOSTemplate_RP.inc' /

